version: "3.9"

services:
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
      - iot-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 15092004        
      MYSQL_DATABASE: iotdb               
      MYSQL_USER: txm           
      MYSQL_PASSWORD: 15092004          
    volumes:
      - ./mysql_data:/var/lib/mysql    
    restart: unless-stopped
    networks:
      - iot-network

networks:
  iot-network:
